# Generated by Django 3.1.2 on 2020-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tyPe', models.CharField(choices=[('cars', 'Cars'), ('Electronics', 'Electronics'), ('Games', 'Games'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Real Estate', 'Real Estate'), ('Food', 'Food'), ('Equipment', 'Equipment'), ('Books', 'Books'), ('pets', 'Pets'), ('Business - Industrial', 'Business'), (' Craftsmen', 'Craftsmenjobs'), ('Electrician services', 'Electrician'), ('Travel - Tourism', 'Travel'), ('Medical Services', 'Medical'), ('Events Services', 'Events'), ('Teaching & Training', 'Teaching'), ('Others', 'Others')], default='Others', max_length=400)),
                ('category', models.CharField(choices=[('goods', 'Goods'), ('services', 'Services')], default='goods', max_length=20)),
            ],
        ),
    ]
