# Generated by Django 3.1.2 on 2020-10-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='type',
            new_name='tyPe',
        ),
    ]
