# Generated by Django 3.1.2 on 2020-10-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201017_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='type',
            new_name='tyPe',
        ),
    ]
